/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart_java( yyin_java )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng_java;
extern FILE *yyin_java, *yyout_java;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext_java. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext_java again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_java_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart_java()), so that the user can continue scanning by
	 * just pointing yyin_java at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext_java is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng_java;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap_java()'s to do buffer switches
 * instead of setting up a fresh yyin_java.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart_java YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer_java YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state_java YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer_java YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer_java YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer_java YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer_java YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer_java( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer_java YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string_java YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes_java YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer_java

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer_java( yyin_java, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer_java( yyin_java, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin_java = (FILE *) 0, *yyout_java = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext_java;
#define yytext_java_ptr yytext_java

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext_java.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_java_ptr = yy_bp; \
	yyleng_java = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
static yyconst short int yy_accept[317] =
    {   0,
        0,    0,   75,   73,   72,   71,   73,   57,   73,   53,
       65,   73,   49,   50,    5,   51,   73,   52,   28,   34,
       33,   46,   56,   45,   42,   42,   42,   67,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   35,   66,   36,   68,   71,   44,    0,
       31,   64,   59,   30,   62,   54,   60,   55,   61,    0,
        0,    0,   40,   63,    0,   28,   69,   47,   43,   48,
       70,   42,   42,   42,   42,   42,   42,   42,   42,   11,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   58,

        0,   39,    0,    0,    0,   40,   29,   28,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,    0,    0,   42,   20,    4,   42,   42,   42,
       42,   42,   42,   42,   42,   12,   42,   42,    0,    0,
       41,   42,   24,   42,   42,   42,   22,   42,   42,   42,
        7,   42,   42,   42,    0,    0,   16,    0,    0,    6,
       42,   42,   42,   42,   42,   42,   42,   42,   32,   26,
       42,   42,   15,    0,   42,   27,   42,   42,   27,   21,
        0,    0,    9,    0,    6,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   23,    0,    0,    0,    0,   42,

       42,    0,    9,   42,   42,   42,   42,   37,   25,   42,
        0,   42,    0,    0,   14,    0,    0,   13,   42,   19,
        0,   42,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    8,    0,   13,   17,    0,   42,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   10,
       18,   18,    0,    8,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   10,    0,
       18,    0,    0,    0,   38,    0,    0,    0,    0,    0,
       20,    0,    0,    0,   20,    0,    0,    0,   24,   22,
        0,    0,    0,   26,    0,    0,    0,    1,    0,   27,

       21,    0,    0,    0,   23,   25,    0,    0,    0,    2,
        0,    0,    0,    0,    3,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   26,   25,   25,   25,   27,   25,   25,   25,
        1,    1,    1,   28,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   25,   46,   47,   48,   49,   50,   51,   25,
       52,   25,   53,   54,   55,   56,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    2,    3,    1,    2,    1,    1,    1,    1,    1,
        4,    1,    1,    1,    5,    1,    6,    1,    7,    1,
        1,    1,    1,    1,    8,    8,    8,    1,    9,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[346] =
    {   0,
        0,    0,  717, 1076, 1076, 1076,  704,  680,  693,  671,
      680,  629,  649,   43, 1076,   42,  652,   46,  642, 1076,
     1076,   38,  635,   39,   56,   57,   60, 1076,    0,   71,
       50,   37,   51,   63,   62,   68,   79,   72,   85,   76,
       89,   84,   95, 1076,  602, 1076, 1076, 1076, 1076,  639,
      623, 1076, 1076, 1076, 1076, 1076, 1076, 1076, 1076,  617,
      615,  133,    0, 1076,  606,  604, 1076, 1076, 1076, 1076,
     1076,    0,   94,   98,   99,  113,  104,  119,  110,  118,
      114,  125,  129,  124,  130,  133,  178,  140,  144,  147,
      156,  151,  155,  166,  167,  160,  171,  170,  181, 1076,

      605,  597,  225,  227,  229,    0,  589,  586,  197,  193,
      206,  210,  213,  163,  214,  220,  219,  202,  225,  237,
      268,  228,  273,  592,  236,  241,  242,  245,  246,  252,
      253,  257,  260,  263,  276,  267,  282,  275,  314,  320,
     1076,  286,  290,  291,  336,  302,  296,  299,  306,  310,
      309,  315,  316,  319,  364,  587,  324,  585,  580,  567,
      327,  328,  342,  339,  335,  346,  355,  345,  349,  354,
      360,  361,  364,   97,  407,  367,  371,  382,  378,  377,
      565,  563,  559,  552,  551,  381,  386,  399,  403,  393,
      406,  396,  439,  452,  402,  539,  453,  454,  546,  418,

      422,  545,  540,  455,  435,  432,  470,  438,  443,  486,
      216,  490,  498,  538,  525,  532,  531,  521,  460,  461,
      488,  474,  535,  584,  508,  505,  481,  510,  488,  465,
      459,  458,  449,  408,  477,  373,  478,  524,  536,  537,
      551,  549,  544,  563,  589,  591,  596,  390,  366,  352,
      304,  285,  265,  264,  218,  567,  214,  601,  539,  583,
      599,  577,  600,  608,  613,  623,  618,  175,  166,  523,
      140,  104,  663,   86,   79,  632,  634,  640,  646,  655,
      654,  660,  669,  668,  677,   63,  677,  679,  687,  688,
      689,  697,  698,  703,  709,  711,   57,   51,  722,  723,

      724,  737,  768,  775,  780,  782,  787,  792,  794,  802,
      804,  806,  814,  816,  818, 1076,  840,  846,  854,  860,
      863,  872,  881,  890,  899,  908,  917,  926,  935,  944,
      953,  962,  971,  980,  988,  996, 1004, 1013, 1022, 1027,
     1035, 1043, 1052, 1060, 1067
    } ;

static yyconst short int yy_def[346] =
    {   0,
      316,    1,  316,  316,  316,  316,  316,  316,  317,  316,
      316,  316,  316,  316,  316,  316,  318,  316,  319,  316,
      316,  316,  316,  316,  320,  320,  320,  316,  321,  320,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,  316,  316,  316,  316,  316,  316,  317,
      317,  316,  316,  316,  316,  316,  316,  316,  316,  322,
      318,  323,  324,  316,  316,  319,  316,  316,  316,  316,
      316,  321,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,  316,

      322,  322,  323,  323,  325,  324,  316,  319,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,  316,  326,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,  323,  323,
      316,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,  316,  327,   30,  328,  326,  326,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,  329,   30,   30,   30,   30,   30,   30,
      330,  327,  327,  328,  328,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,  329,  329,  316,  331,   30,

       30,  330,  330,   30,   30,   30,   30,   30,   30,   30,
      332,   30,  316,  333,  329,  334,  331,  331,   30,   30,
      316,   30,  335,  335,  316,  336,  332,  332,  337,  338,
      333,  333,  334,  334,   30,  316,   30,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  339,  336,  336,
      332,  340,  338,  338,  316,  341,  342,  335,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  339,  339,  316,
      340,  316,  341,  342,  342,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  343,  316,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  343,  343,  246,  246,

      246,  246,  335,  335,  335,  335,  344,  335,  335,  344,
      335,  335,  335,  345,  345,    0,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316
    } ;

static yyconst short int yy_nxt[1133] =
    {   0,
        4,    5,    6,    7,    5,    8,    9,   10,   11,   12,
        4,    4,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   25,
       30,   31,   32,   33,   34,   35,   25,   36,   25,   25,
       25,   25,   37,   25,   38,   39,   40,   41,   25,   42,
       43,   25,   44,   45,   46,   47,   56,   58,   62,   67,
       68,   70,   71,   63,   59,   57,   60,   60,   64,   54,
       60,  298,   61,   61,   72,   72,   61,  298,   72,   77,
       80,   60,   73,  298,   72,   72,   78,   61,   72,   72,
      275,   81,   82,   79,   73,   73,   73,  275,  197,   72,

       83,  197,   87,   84,   74,   86,   85,   73,   73,   88,
       89,   73,   90,   73,   75,   73,   76,   91,   93,   73,
       92,   73,   73,   94,   73,   96,   95,   98,   73,   73,
       73,   99,   73,  286,   97,  104,  104,   73,   73,   73,
       73,   73,  110,  109,   73,  105,  111,   73,  114,   73,
      112,  113,  115,   73,  270,   73,   73,   73,   73,   73,
      117,   73,   73,   73,   73,  118,  116,  120,   73,   73,
       73,  119,   73,   73,   73,  121,   73,  269,   73,  123,
      122,  130,  123,   73,  125,   73,  269,   73,  124,   73,
       73,  126,   73,  128,   73,  132,   73,  127,   73,  129,

       73,   73,  131,   73,  133,  134,   73,  137,  147,   73,
       73,   73,   73,   73,   73,   73,   73,  228,  138,  135,
      228,   73,  136,   73,   73,  275,   73,  104,  104,  104,
      104,  140,  140,  143,  142,  144,   73,  105,   73,  105,
       73,  105,   73,  145,  146,   73,  141,   73,  152,   73,
      150,   73,  151,   73,  153,   73,   73,   73,   73,   73,
      148,  149,   73,   73,   73,   73,  154,  272,   73,  155,
       73,  157,  155,   73,  123,  254,  254,  123,  156,  161,
       73,   73,   73,  158,   73,   73,   73,   73,   73,   73,
       73,   73,  164,  163,  162,   73,   73,   73,   73,  270,

       73,  165,   73,   73,  166,   73,  168,  167,   73,  169,
       73,   73,   73,   73,  170,  171,  104,  104,   73,   73,
       73,   73,  104,  104,  251,   73,  105,   73,  172,   73,
      173,   73,  105,   73,   73,   73,   73,  174,  175,   73,
      174,   73,   73,  177,   73,   73,  176,   73,  169,   73,
      178,   73,   73,   73,   73,   73,  179,  187,   73,   73,
       73,   73,   73,  250,   73,  155,  180,   73,  155,   73,
       73,   73,  186,   73,  181,  188,  189,  250,   73,   73,
      190,   73,   73,  191,   73,   73,  192,   73,   73,   73,
       73,   73,   73,  194,   73,  193,  195,   73,   73,   73,

       73,  269,  255,   73,   73,   73,   73,   73,  198,   73,
       73,  198,   73,  200,   73,  180,   73,  199,  201,  234,
       73,   73,   73,   73,   73,   73,   73,   73,  204,   73,
      206,   73,  210,  205,  207,  208,   73,  209,   73,   73,
      211,   73,   73,  211,   73,   73,   73,   73,   73,   73,
       73,   73,   73,  213,  197,  198,  213,  197,  198,  221,
      234,   73,  214,   73,  216,   73,  219,   73,  207,  232,
      232,  223,  215,  220,  224,   73,  254,   73,   73,  222,
       73,   73,   73,   73,   73,  212,   73,  225,   73,  229,
      225,  229,  229,  235,  229,   73,  226,   73,   73,  213,

       73,  251,  213,   73,   73,   73,   73,  237,  230,  225,
      207,  228,  225,   73,  228,   73,  250,   73,  248,   73,
       73,   73,   73,   73,  229,  256,  236,  229,  256,   73,
      251,   73,  218,   73,  257,   73,  223,  256,  256,  223,
      256,  256,  218,  234,  215,  256,  257,  257,  256,  232,
      256,  203,  256,  256,  257,  256,  203,  218,  215,  257,
      239,  257,  185,  185,  256,  240,  241,  256,  256,  242,
      183,  256,  243,  257,  183,  238,  203,  257,  160,  238,
      259,  244,  277,  258,  245,  223,  263,  260,  223,  262,
      256,  160,  256,  256,  261,  256,  185,  256,  183,  257,

      256,  257,  256,  160,  108,  256,  257,  107,  102,  239,
      264,  257,  278,  238,  240,  246,  102,  238,  242,  238,
      280,  247,  108,  238,  107,   60,  238,  260,  102,   51,
      244,  266,  265,  245,  261,  238,  238,  282,  267,  238,
      238,  279,  238,  238,  238,   51,  276,  281,  238,  238,
      283,  238,  284,  238,  238,  100,  238,   69,  238,  238,
       66,  238,   60,  238,  287,  285,  238,  287,  238,  288,
      238,   55,  238,  257,  289,  238,  238,  238,  287,   54,
      238,  287,  238,  238,  292,  290,  238,  257,   53,  238,
      238,  238,  291,   52,  238,  238,  238,  238,  238,   51,

      238,  294,   49,  238,  238,  238,   48,  293,  238,  238,
      296,  238,  238,  238,  295,  238,  316,  238,  316,  238,
      238,  299,  238,  238,  238,  238,  316,  238,  238,  238,
      238,  238,  238,  238,  238,  302,  300,  238,  238,  238,
      238,  238,  316,  238,  301,  238,  238,  238,  316,  238,
      316,  238,  238,  316,  238,  303,  304,  305,  238,  238,
      238,  316,  238,  238,  238,  238,  238,  238,  306,  256,
      316,  316,  307,  238,  316,  316,  256,  238,  257,  256,
      238,  256,  316,  309,  256,  257,  309,  316,  256,  316,
      257,  256,  257,  256,  316,  309,  256,  257,  309,  316,

      316,  316,  257,  287,  257,  256,  287,  256,  256,  308,
      256,  316,  257,  316,  257,  256,  257,  256,  314,  287,
      256,  311,  287,  316,  257,  316,  257,  316,  257,  316,
      316,  316,  316,  316,  316,  312,  316,  316,  316,  313,
       50,   50,  316,   50,   50,   50,   50,   50,   50,   61,
      316,   61,  316,   61,   65,   65,  316,   65,   65,   65,
       65,   65,   65,   73,  316,   73,   73,   73,   73,   72,
       72,   72,  101,  101,  316,  101,  101,  101,  101,  101,
      101,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      106,  106,  316,  106,  106,  106,  106,  106,  106,  139,

      139,  139,  139,  139,  139,  139,  139,  139,  159,  159,
      316,  159,  159,  159,  159,  159,  159,  182,  182,  316,
      182,  182,  182,  182,  182,  182,  184,  184,  316,  184,
      184,  184,  184,  184,  184,  196,  196,  316,  196,  196,
      196,  196,  196,  196,  202,  202,  316,  202,  202,  202,
      202,  202,  202,  217,  217,  316,  217,  217,  217,  217,
      217,  217,  227,  227,  316,  227,  227,  227,  227,  227,
      227,  231,  231,  316,  231,  231,  231,  231,  231,  231,
      233,  233,  316,  233,  233,  233,  233,  233,  233,  238,
      316,  316,  316,  316,  316,  238,  249,  249,  316,  249,

      249,  249,  249,  249,  249,  252,  316,  316,  316,  316,
      316,  252,  252,  253,  253,  316,  253,  253,  253,  253,
      253,  253,  268,  268,  316,  268,  268,  268,  268,  268,
      268,  271,  316,  271,  271,  271,  273,  316,  273,  316,
      316,  316,  273,  274,  274,  316,  274,  274,  274,  274,
      274,  274,  297,  297,  316,  297,  297,  297,  297,  297,
      297,  310,  316,  310,  316,  316,  316,  310,  315,  316,
      315,  316,  316,  316,  315,    3,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316
    } ;

static yyconst short int yy_chk[1133] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   14,   16,   18,   22,
       22,   24,   24,   18,   16,   14,   25,   26,   18,   27,
       27,  298,   25,   26,   25,   26,   27,  297,   27,   31,
       32,   30,   32,  286,   25,   26,   31,   30,   27,   30,
      275,   33,   34,   31,   33,   31,   33,  274,  174,   30,

       34,  174,   36,   34,   26,   35,   34,   35,   34,   36,
       36,   36,   37,   36,   30,   38,   30,   38,   39,   40,
       38,   40,   37,   40,   37,   41,   40,   42,   39,   42,
       39,   43,   41,  272,   41,   62,   62,   73,   43,   73,
       43,   74,   75,   74,   75,   62,   76,   77,   78,   77,
       77,   77,   79,   79,  271,   79,   76,   81,   76,   81,
       81,   80,   78,   80,   78,   82,   80,   84,   82,   84,
       82,   83,   83,   85,   83,   85,   86,  269,   86,   87,
       86,   92,   87,   88,   88,   88,  268,   89,   87,   89,
       90,   89,   90,   91,   92,   94,   92,   90,   93,   91,

       93,   91,   93,   96,   95,   96,  114,   98,  114,   94,
       95,   94,   95,   98,   97,   98,   97,  211,   99,   97,
      211,   87,   97,   87,   99,  257,   99,  103,  103,  104,
      104,  105,  105,  110,  109,  111,  110,  103,  110,  104,
      109,  105,  109,  112,  113,  118,  105,  118,  118,  111,
      116,  111,  117,  112,  119,  112,  113,  115,  113,  115,
      115,  115,  117,  116,  117,  116,  120,  255,  119,  121,
      119,  122,  121,  122,  123,  254,  253,  123,  121,  125,
      120,  125,  120,  123,  126,  127,  126,  127,  128,  129,
      128,  129,  130,  129,  128,  130,  131,  130,  131,  252,

      132,  131,  132,  133,  132,  133,  134,  133,  134,  135,
      136,  121,  136,  121,  137,  138,  139,  139,  138,  135,
      138,  135,  140,  140,  251,  137,  139,  137,  142,  142,
      144,  142,  140,  143,  144,  143,  144,  145,  146,  147,
      145,  147,  148,  149,  148,  146,  148,  146,  152,  149,
      150,  149,  151,  150,  151,  150,  153,  162,  152,  153,
      152,  153,  154,  250,  154,  155,  154,  157,  155,  157,
      161,  162,  161,  162,  155,  163,  164,  249,  165,  145,
      165,  145,  164,  166,  164,  163,  167,  163,  168,  166,
      168,  166,  169,  171,  169,  168,  172,  170,  167,  170,

      167,  248,  236,  171,  172,  171,  172,  173,  175,  173,
      176,  175,  176,  177,  177,  178,  177,  175,  179,  234,
      180,  179,  180,  179,  186,  178,  186,  178,  186,  187,
      188,  187,  192,  187,  189,  190,  190,  191,  190,  192,
      193,  192,  188,  193,  188,  195,  189,  195,  189,  191,
      175,  191,  175,  194,  197,  198,  194,  197,  198,  204,
      233,  200,  194,  200,  198,  201,  200,  201,  205,  232,
      231,  207,  197,  201,  207,  206,  230,  206,  205,  206,
      205,  208,  193,  208,  193,  193,  209,  210,  209,  229,
      210,  212,  229,  219,  212,  194,  210,  194,  204,  213,

      204,  227,  213,  219,  220,  219,  220,  222,  213,  225,
      237,  228,  225,  207,  228,  207,  226,  222,  225,  222,
      235,  237,  235,  237,  270,  238,  221,  270,  238,  210,
      228,  210,  218,  212,  238,  212,  223,  239,  240,  223,
      239,  240,  217,  216,  215,  243,  239,  240,  243,  214,
      242,  203,  241,  242,  243,  241,  202,  199,  196,  242,
      223,  241,  185,  184,  244,  223,  223,  244,  256,  223,
      183,  256,  223,  244,  182,  259,  181,  256,  160,  259,
      240,  223,  259,  239,  223,  224,  243,  241,  224,  242,
      245,  159,  246,  245,  241,  246,  158,  247,  156,  245,

      247,  246,  258,  124,  108,  258,  247,  107,  102,  224,
      244,  258,  260,  262,  224,  224,  101,  262,  224,  260,
      262,  224,   66,  260,   65,   61,  260,  246,   60,   51,
      224,  246,  245,  224,  246,  261,  263,  264,  247,  261,
      263,  261,  261,  263,  264,   50,  258,  263,  264,  265,
      265,  264,  266,  265,  267,   45,  265,   23,  267,  266,
       19,  267,   17,  266,  273,  267,  266,  273,  276,  276,
      277,   13,  276,  273,  277,  276,  278,  277,  287,   12,
      278,  287,  279,  278,  280,  278,  279,  287,   11,  279,
      281,  280,  279,   10,  281,  280,  282,  281,  280,    9,

      282,  283,    8,  282,  284,  283,    7,  282,  284,  283,
      285,  284,  283,  285,  284,  288,    3,  285,    0,  288,
      285,  288,  288,  289,  290,  291,    0,  289,  290,  291,
      289,  290,  291,  292,  293,  293,  291,  292,  293,  294,
      292,  293,    0,  294,  292,  295,  294,  296,    0,  295,
        0,  296,  295,    0,  296,  295,  296,  299,  299,  300,
      301,    0,  299,  300,  301,  299,  300,  301,  302,  303,
        0,    0,  303,  302,    0,    0,  304,  302,  303,  304,
      302,  305,    0,  306,  305,  304,  306,    0,  307,    0,
      305,  307,  306,  308,    0,  309,  308,  307,  309,    0,

        0,    0,  308,  310,  309,  311,  310,  312,  311,  304,
      312,    0,  310,    0,  311,  313,  312,  314,  313,  315,
      314,  308,  315,    0,  313,    0,  314,    0,  315,    0,
        0,    0,    0,    0,    0,  311,    0,    0,    0,  312,
      317,  317,    0,  317,  317,  317,  317,  317,  317,  318,
        0,  318,    0,  318,  319,  319,    0,  319,  319,  319,
      319,  319,  319,  320,    0,  320,  320,  320,  320,  321,
      321,  321,  322,  322,    0,  322,  322,  322,  322,  322,
      322,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      324,  324,    0,  324,  324,  324,  324,  324,  324,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  326,  326,
        0,  326,  326,  326,  326,  326,  326,  327,  327,    0,
      327,  327,  327,  327,  327,  327,  328,  328,    0,  328,
      328,  328,  328,  328,  328,  329,  329,    0,  329,  329,
      329,  329,  329,  329,  330,  330,    0,  330,  330,  330,
      330,  330,  330,  331,  331,    0,  331,  331,  331,  331,
      331,  331,  332,  332,    0,  332,  332,  332,  332,  332,
      332,  333,  333,    0,  333,  333,  333,  333,  333,  333,
      334,  334,    0,  334,  334,  334,  334,  334,  334,  335,
        0,    0,    0,    0,    0,  335,  336,  336,    0,  336,

      336,  336,  336,  336,  336,  337,    0,    0,    0,    0,
        0,  337,  337,  338,  338,    0,  338,  338,  338,  338,
      338,  338,  339,  339,    0,  339,  339,  339,  339,  339,
      339,  340,    0,  340,  340,  340,  341,    0,  341,    0,
        0,    0,  341,  342,  342,    0,  342,  342,  342,  342,
      342,  342,  343,  343,    0,  343,  343,  343,  343,  343,
      343,  344,    0,  344,    0,    0,    0,  344,  345,    0,
      345,    0,    0,    0,  345,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext_java;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
#include "scanner.h"
#line 726 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap_java YY_PROTO(( void ));
#else
extern int yywrap_java YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_java_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyin_javaput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext_java, yyleng_java, 1, yyout_java )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin_java )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin_java ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin_java )) == 0) \
		  && ferror( yyin_java ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex_java YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext_java and yyleng_java
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 5 "scanner.l"


#line 880 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin_java )
			yyin_java = stdin;

		if ( ! yyout_java )
			yyout_java = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer_java( yyin_java, YY_BUF_SIZE );

		yy_load_buffer_state_java();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext_java. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 317 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1076 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 7 "scanner.l"
return IMPORT;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 8 "scanner.l"
return CLASS;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 9 "scanner.l"
return INTERFACE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 10 "scanner.l"
return NEW;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 11 "scanner.l"
return COMMA;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 13 "scanner.l"
return IF;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 14 "scanner.l"
return ELSE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 15 "scanner.l"
return WHILE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 16 "scanner.l"
return FOR;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 17 "scanner.l"
return SWITCH;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 18 "scanner.l"
return DO;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 19 "scanner.l"
return TRY;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 20 "scanner.l"
return CATCH;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 21 "scanner.l"
return CASE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 22 "scanner.l"
return BREAK;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 23 "scanner.l"
return GOTO;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 24 "scanner.l"
return CONTINUE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 25 "scanner.l"
return THROW;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 26 "scanner.l"
return FINALLY;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 28 "scanner.l"
return tINT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 29 "scanner.l"
return tFLOAT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 30 "scanner.l"
return tCHAR;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 31 "scanner.l"
return tSTRING;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 32 "scanner.l"
return tBOOL;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 33 "scanner.l"
return tSTATIC;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 34 "scanner.l"
return tVOID;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 35 "scanner.l"
return tCONST;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 37 "scanner.l"
return INT;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 38 "scanner.l"
return FLOAT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 39 "scanner.l"
return CHAR;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 40 "scanner.l"
return STRING;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 41 "scanner.l"
return BOOL;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 43 "scanner.l"
return SEMICOLON;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 44 "scanner.l"
return COLON;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 45 "scanner.l"
return LEFT_BRACE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 46 "scanner.l"
return RIGHT_BRACE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 47 "scanner.l"
return RETURN;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 48 "scanner.l"
return FUNCTION;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 49 "scanner.l"
return FUNCTION_CALL;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 50 "scanner.l"
return LINE_COMMENT;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 51 "scanner.l"
return BLOCK_COMMENT;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 52 "scanner.l"
return VAR_NAME;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 54 "scanner.l"
return EQ;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 55 "scanner.l"
return NE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 56 "scanner.l"
return GT;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 57 "scanner.l"
return LT;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 58 "scanner.l"
return LE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 59 "scanner.l"
return GE;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 61 "scanner.l"
return MUL;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 62 "scanner.l"
return ADD;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 63 "scanner.l"
return SUB;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 64 "scanner.l"
return DIV;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 65 "scanner.l"
return MOD;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 66 "scanner.l"
return INC;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 67 "scanner.l"
return DEC;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 69 "scanner.l"
return ASSIGNMENT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 70 "scanner.l"
return NOT;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 71 "scanner.l"
return OR;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 72 "scanner.l"
return AND;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 73 "scanner.l"
return ADDE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 74 "scanner.l"
return SUBE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 75 "scanner.l"
return MULE;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 76 "scanner.l"
return DIVE;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 77 "scanner.l"
return MODE;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 78 "scanner.l"
return BAND;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 79 "scanner.l"
return BOR;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 80 "scanner.l"
return BXOR;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 81 "scanner.l"
return BNOT;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 82 "scanner.l"
return BSHL;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 83 "scanner.l"
return BSHR;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 87 "scanner.l"
return NEWLINE;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 88 "scanner.l"
;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 89 "scanner.l"
printf("wat.");
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 90 "scanner.l"
ECHO;
	YY_BREAK
#line 1333 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_java_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin_java at a new source and called
			 * yylex_java().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin_java;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_java_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_java_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap_java() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext_java, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_java_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_java_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_java_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_java_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex_java */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_java_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_java_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_java_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart_java( yyin_java );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_java_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_java_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 317 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 317 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 316);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext_java */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_java_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyin_javaput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_java_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart_java( yyin_java );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap_java() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyin_javaput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_java_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext_java */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart_java( FILE *input_file )
#else
void yyrestart_java( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer_java( yyin_java, YY_BUF_SIZE );

	yy_init_buffer_java( yy_current_buffer, input_file );
	yy_load_buffer_state_java();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer_java( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer_java( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state_java();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap_java()) processing, but the only time this flag
	 * is looked at is after yywrap_java() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state_java( void )
#else
void yy_load_buffer_state_java()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_java_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin_java = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer_java( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer_java( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer_java()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer_java()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer_java( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer_java( YY_BUFFER_STATE b )
#else
void yy_delete_buffer_java( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer_java( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer_java( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer_java( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer_java( YY_BUFFER_STATE b )
#else
void yy_flush_buffer_java( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state_java();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer_java( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer_java( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer_java()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer_java( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string_java( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string_java( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes_java( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes_java( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes_java( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes_java()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer_java( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes_java()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext_java. */ \
		yytext_java[yyleng_java] = yy_hold_char; \
		yy_c_buf_p = yytext_java + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng_java = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_java_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex_java();
	return 0;
	}
#endif
#line 90 "scanner.l"


int yywrap_java(void) {
    return 1;
}
